### ISSUE TITLE
Getting This Error

### ISSUE THREAD

**Issue by Spalar** [rohitnairtech/YoutubeChannelAllVideoThumbnailDownloader#1]
I don't know what i am working with here.This is the error i get in my debug console VS Code.

[errorlog1.txt](https://github.com/rohitnairtech/YoutubeChannelAllVideoThumbnailDownloader/files/3100117/errorlog1.txt)

**Comment by archmord** [comment]
you system dont have required modules installed to work it properly

**Comment by rohitnairtech** [comment]
Solved
